/**
 * Utilities
 */
export const REQUEST_START = 'REQUEST_START'
export const REQUEST_END = 'REQUEST_END'

export const ALERT_SUCCESS = 'ALERT_SUCCESS'
export const ALERT_ERROR = 'ALERT_ERROR'

/**
 * User Actions
 */
export const USER_SET = 'USER_SET'
export const USER_UNSET = 'USER_UNSET'

/**
 * Client Actions
 */
export const CLIENTS_REQUEST = 'CLIENTS_REQUEST'
export const CLIENTS_REQUEST_SUCCESS = 'CLIENTS_REQUEST_SUCCESS'
export const CLIENTS_REQUEST_ERROR = 'CLIENTS_REQUEST_ERROR'
export const CLIENT_EDIT_REQUEST = 'CLIENT_EDIT_REQUEST'
export const CLIENT_EDIT_SUCCESS = 'CLIENT_EDIT_SUCCESS'
export const CLIENT_EDIT_ERROR = 'CLIENT_EDIT_ERROR'

/**
 * Signup Actions
 */
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_ERROR = 'SIGNUP_ERROR'

/**
 * Login Actions
 */
export const AUTH_REQUEST = 'AUTH_REQUEST'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_ERROR = 'AUTH_ERROR'

/**
 * Logout Actions
 */
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'

/**
 * User Orders Actions
 */
export const USER_ORDERS_REQUEST = 'USER_ORDERS_REQUEST'
export const USER_ORDERS_REQUEST_SUCCESS = 'USER_ORDERS_REQUEST_SUCCESS'
export const USER_ORDERS_SUBMIT = 'USER_ORDERS_SUBMIT'
export const USER_ORDERS_SUBMIT_SUCCESS = 'USER_ORDERS_SUBMIT_SUCCESS'
export const USER_ORDERS_ERROR = 'USER_ORDERS_ERROR'
export const USER_ORDER_UPDATE = 'USER_ORDER_UPDATE'
export const USER_ORDER_UPDATE_SUCCESS = 'USER_ORDER_UPDATE_SUCCESS'

/**
 * Admin Orders Action
 */
export const ADMIN_ORDERS_REQUEST = 'ADMIN_ORDERS_REQUEST'
export const ADMIN_ORDERS_REQUEST_SUCCESS = 'ADMIN_ORDERS_REQUEST_SUCCESS'
export const ADMIN_ORDERS_ERROR = 'ADMIN_ORDERS_ERROR'
export const ADMIN_ORDER_UPDATE = 'ADMIN_ORDER_UPDATE'
export const ADMIN_ORDER_UPDATE_SUCCESS = 'ADMIN_ORDER_UPDATE_SUCCESS'
